services:

  postgres:
    image: postgres:16
    container_name: csrag-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - csrag-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  csrag:
    image: YOUR_DOCKERHUB_USERNAME/csrag:latest
    container_name: csrag
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_URI: postgresql://postgres:postgres@csrag-postgres:5432/postgres?sslmode=disable
    networks:
      - csrag-net
    restart: unless-stopped

networks:
  csrag-net:
    name: csrag-net

volumes:
  postgres_data:
